### ISSUE TITLE
フィルターのタイムスタンプが指定しづらい

### ISSUE THREAD

**Issue by okkez** [clear-code/sharetary#23]
年月日の指定が valid でない年月日を指定できてしまう。
例えば、年月日にマイナスが指定できたり、月に13以上を指定できたりしてしまう。
時分秒も同様。

範囲外の値を指定できないようにしてほしい。
あと、年はデータベースに入っている最大と最小で入力できる範囲を決められるといいと思う。

年月日をカレンダーで指定できるとさらに良いと思う。
時分秒は選べなくてもいいような気がした。

**Comment by okkez** [comment]
詳しく調べてませんが、範囲外の値を指定するとエラーになることがあるようです。
こちらで確認したのは、開始の年だけに -1 を設定するとエラーになりました。

**Comment by piroor** [comment]
#2 をクローズしてこっちで続けた方がよいでしょうか？

Bootstrap 3用のDatetime Pickerの実装があるのでそれを使おうと最初は思ったのですが、ビルドシステムと併用する前提になっているらしく、自分がロートル過ぎて今の仕組みにうまく組み込むやり方が分からずお手上げになってしまっています。
https://eonasdan.github.io/bootstrap-datetimepicker/
Bootstrap 2用の物の方が組み込み方が簡単（単純）だったので、これがそのまま使えればよかったんですが……
http://tarruda.github.io/bootstrap-datetimepicker/

**Comment by kou** [comment]
個人的には、年月日とかを個別に入力するフォームじゃなくて、入力フォーマットをフォームの横に書いておいて、テキスト入力のフォームにした方が使い勝手がよいです。（個人的な意見をもう少し言うと、カレンダーのUIよりもテキスト入力の方がコピペできて私は便利。）

**Comment by okkez** [comment]
すみません。#2 を見てなかったです。

**Comment by piroor** [comment]
実際触ってみたら個別に入力するフォームはやはり使いにくい上に特にトラブルが減るわけでもなさそうだったので、ひとまず https://github.com/clear-code/sharetary/issues/23#issuecomment-111898225 の方式にする事にします。

**Comment by piroor** [comment]
Datetime Pickerを使うようにしました。
テキストとしてのコピペも可能です。
