### ISSUE TITLE
Is `database` dir packed on a purpose?

### ISSUE THREAD

**Issue by ChALkeR** [clear-code/sharetary#5]
_Disclaimer: I do not use the package, this was found during automated npm packages downloading._

Your current package size is 0.9 MiB packed, **271 MiB unpacked**. 269 MiB of that are inside the `database` dir. I suspect that this probably got packed to the release by mistake.

If you don't want to pack that directory, add it to the `.gitignore` and/or `.npmingore`.

**Comment by piroor** [comment]
Oops, I forgot to remove it from the package... Thanks!!
